### ISSUE TITLE
Strange behaviour when rebinding CAPS with LCTRL and adding some additional bindings

### ISSUE THREAD

**Issue by yunmikun2** [arnarg/waybind#6]
I've been trying to rebind `LControl` with `CapsLock` (and vice versa) and bind `CapsLock+M` to `Enter`. I composed the config that handles different cases of the modifier so that it should act differently on just `CapsLock` and `CapsLock+M`.

## Config

Considering the README.md mentions that it first looks for `with_modifiers` section, then goes to `to` section, I tried the following variants:

### v1

```
  - from: KEY_M
    with_modifiers:
      - modifier: KEY_CAPSLOCK
        to: KEY_ENTER

  - from: KEY_LEFTCTRL
    to: KEY_CAPSLOCK

  - from: KEY_CAPSLOCK
    to: KEY_LEFTCTRL
```

### v2

```
  - from: KEY_LEFTCTRL
    to: KEY_CAPSLOCK

  - from: KEY_CAPSLOCK
    to: KEY_LEFTCTRL
    with_modifiers:
      - modifier: KEY_M
        to: KEY_ENTER
```

## Expected behavior

When I press `CapsLock+<something>` I get `Ctrl+<something>`.
When I press `CapsLock+M` I get `Enter`.
When I press `LCtrl` I get `CapsLock`.

## Actual behavior

When I press `CapsLock+<something>` I get `Ctrl+<something>`.
When I press `CpasLock+M` I get `Ctrl+Enter`.
When I press `LCtrl` I get `CapsLock`.
